services:
  selenoid:
    network_mode: bridge
    image: "aerokube/selenoid:latest"
    container_name: selenoid
    volumes:
      - "D:/Projects/aqa_demo/src/main/resources/selenoid/config:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=D:/Projects/aqa_demo/src/main/resources/selenoid/video
    command: [ "-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs" ]
    ports:
      - "6672:4444"

  selenoid-ui:
    network_mode: bridge
    image: "aerokube/selenoid-ui:latest"
    container_name: selenoid-ui
    links:
      - selenoid
    ports:
      - "8090:8080"
    command: [ "--selenoid-uri", "http://selenoid:4444" ]

  jenkins:
    image: jenkins/jenkins:lts
    volumes:
      - "D:/Programs/Jenkins:/var/jenkins_home"
    ports:
      - 8000:8080
    network_mode: bridge
